
- name: A playbook to install kubectl
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: 1. Update APT Package Manager
    shell:
      cmd: sudo apt-get update

  - name: 2. Install dependency packages
    apt:
      name={{ item }}
    with_items:
      - apt-transport-https 
      - ca-certificates
      - gnupg-agent 
      - software-properties-common
      - conntrack

  - name: 3. Get APT Key
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add

  - name: 4. Add APT Repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

  - name: 5. Install Minikube
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

  - name: 6. Add rights to minikube
    shell:
      cmd: chmod +x minikube

  - name: 7. Move minikube
    shell:
      cmd: mv minikube /usr/local/bin/

  - name: 8. Install kubectl
    shell:
      cmd: apt-get install -y kubectl 

  - name: 9. Run updates
    shell:
      cmd: apt-get update 

  - name: 10. Start minikube
    become: no
    shell:
      cmd: minikube start

